name = input('Please Enter your name---> ')
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t    *")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t   ***")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t  *****")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t *******")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t Hi" + name + '')
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t *******")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t  *****")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t   ***")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t    *")