print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t    *")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t   ***")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t  *****")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t *******")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t *******")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t  *****")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t   ***")
print(f"\t\t\t\t\t\t\t\t\t\t\t\t\t\t    *")