pera = eval(input('Enter amount to deposit ---> '))
print(" -------------------------------------")
print('  - 1,000 ')
print('  -   500 ')
print('  -   200 ')
print('  -   100 ')
print('  -    50 ')
print('  -    20 ')
print('  -    10 ')
print('  -     5 ')
print('  -     1 ')