name = input('Please input your name here> ')
age = input('Please input your age> ')
birthdate = input('Please input your birthdate here> ')
birthmonth = input('Please input your birthmonth here> ')
birthyear = input('Please input your birthyear here> ')
adress = input('Please input your adress here> ')
mobile = input('Please input your mobile here> ')
email = input('Please input your email here> ')
print("\n\n\n\nHello, Myname is " , name , "\b.\nI'm " , age , "\b.\nMy Birthday is in" , birthmonth , birthdate , birthyear, "\b.\nl live in" , adress , "\b.\nMy mobile number is" , mobile , "\b.\nYou may also contact me through my email as" , email , "\b.\n\n\n")